language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
before_script:
  - npm start -- --silent &
script:
  - npm run test -- -u
  - npm run cypress:run